version: '3.7'
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:24.11"
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ./clickhouse-01-data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d
    ports:
      - "5123:8123"
      - "5001:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03


  clickhouse-02:
    image: "clickhouse/clickhouse-server:24.11"
    container_name: clickhouse-02
    hostname: clickhouse-02
    volumes:
      - ./clickhouse-02-data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d
    ports:
      - "5124:8123"
      - "5002:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:24.11"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    volumes:
     - ./clickhouse-keeper-01/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "5181:9181"

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:24.11"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    volumes:
     - ./clickhouse-keeper-02/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "5182:9181"

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:24.11"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    volumes:
     - ./clickhouse-keeper-03/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "5183:9181"

  metabase:
    image: "metabase/metabase:v0.51.6.1"
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_PLUGINS_DIR: /plugins
    volumes:
      - ./metabase-data:/metabase-data
      - ./plugins/clickhouse.jar:/plugins/clickhouse.jar